### ISSUE TITLE
Can u build release for Windows ?

### ISSUE THREAD

**Issue by leftspace89** [vicr123/QtcDRP#1]
Thanks for this plugin but I want use this on windows 👍

**Comment by vicr123** [comment]
Unfortunately I don't have a Windows computer that I can build this on :(

**Comment by viveksh1** [comment]
@vicr123 You can use a virtual machine.

**Comment by leftspace89** [comment]
lol Im not using qt anymore but thanks 💯

**Comment by viveksh1** [comment]
@leftspace89 I want a rich presence when I use qt.
